
from datetime import (
    datetime,
    timezone
)

from database.db import get_db_connection

from utils.logger import log_activity

import math

import ipaddress

from config.constants import (
    ALLOWED_DEVICE_STATUSES
)


   # Register Device Service


def register_device_service(
    current_user_id,
    current_username,
    data
):
    """
    Responsibility:
        Register a new device for monitoring in the CyberWatch system.

    Business Rules:
        • Only authenticated users may register devices.
        • Hostname is required.
        • IP address is required.
        • Operating system is required.
        • Device status is required.
        • Hostname must be unique.
        • IP address must be unique.
        • IP address must be valid.
        • Device status must be one of the allowed statuses.
        • Registration timestamp is generated by the system.
        • Device registration must be recorded in the audit log.

    Returns:
        JSON response containing the newly registered device.
    """

    hostname = data.get("hostname")
    ip_address = data.get("ip_address")
    operating_system = data.get("operating_system")
    status = data.get("status", "active")

    # Validate required fields
    if not hostname or not ip_address or not operating_system or not status:

        return {
            "status": "error",
            "message": "Hostname, IP address, operating system and status are required"
        }, 400

    # Business Rule:
    # Validate IP address format
    try:

        ipaddress.ip_address(ip_address)

    except ValueError:

        return {
            "status": "error",
            "message": "Invalid IP address"
        }, 400

    # Business Rule:
    # Validate allowed device status
    if status not in ALLOWED_DEVICE_STATUSES:

        return {
            "status": "error",
            "message": "Invalid device status"
        }, 400

    connection = get_db_connection()

    cursor = connection.cursor()

    # Business Rule:
    # Hostname must be unique
    # cursor.execute(
     #   """
      #  SELECT id
       # FROM devices
       # WHERE hostname = ?
       # """,
       # (hostname,)
    #)

    #existing_hostname = cursor.fetchone()

    #if existing_hostname:

    #    connection.close()

      #  return {
       #     "status": "error",
       #     "message": "Hostname already exists"
        #}, 409

    # Business Rule:
    # IP address must be unique
    cursor.execute(
        """
        SELECT id
        FROM devices
        WHERE ip_address = ?
        """,
        (ip_address,)
    )

    existing_ip = cursor.fetchone()

    if existing_ip:

        connection.close()

        return {
            "status": "error",
            "message": "IP address already exists"
        }, 409

    timestamp = (
        datetime.now(timezone.utc)
        .isoformat()
        .replace("+00:00", "Z")
    )

    # Register the device
    cursor.execute(
        """
        INSERT INTO devices
        (
            hostname,
            ip_address,
            operating_system,
            status,
            registered_at
        )
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            hostname,
            ip_address,
            operating_system,
            status,
            timestamp
        )
    )

    connection.commit()

    device_id = cursor.lastrowid

    # Record the registration activity for auditing purposes
    log_activity(
        current_user_id,
        current_username,
        f"Registered device '{hostname}' ({ip_address})"
    )

    connection.close()

    return {
        "status": "success",
        "message": "Device registered successfully",
        "device": {
            "id": device_id,
            "hostname": hostname,
            "ip_address": ip_address,
            "operating_system": operating_system,
            "status": status,
            "registered_at": timestamp
        }
    }, 201


def get_devices_service(
    search,
    page,
    per_page
):
    """
    Responsibility:
        Retrieve registered devices from the CyberWatch inventory
        with optional search filtering and pagination.

    Business Rules:
        • Only authenticated users may retrieve devices.
        • Search is optional.
        • Search applies to hostname, IP address, operating system and status.
        • Results are ordered by newest registered device first.
        • Page number must be greater than zero.
        • Per-page value must be greater than zero.
        • Maximum per-page value is 100.
        • No audit log is required.

    Returns:
        Paginated list of registered devices.
    """

    # Remove leading/trailing spaces
    search = (search or "").strip()

    # Validate page number
    if page < 1:

        return {
            "status": "error",
            "message": "Page number must be greater than zero"
        }, 400

    # Validate per_page
    if per_page < 1:

        return {
            "status": "error",
            "message": "Per page value must be greater than zero"
        }, 400

    if per_page > 100:

        return {
            "status": "error",
            "message": "Maximum per page value is 100"
        }, 400

    connection = get_db_connection()

    cursor = connection.cursor()

    search_value = f"%{search}%"

    # Retrieve total matching records
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM devices
        WHERE
            deleted = 0
            AND (
                hostname LIKE ?
                OR ip_address LIKE ?
                OR operating_system LIKE ?
                OR status LIKE ?
            )
        """,
        (
            search_value,
            search_value,
            search_value,
            search_value
        )
    )

    total_records = cursor.fetchone()[0]

    total_pages = math.ceil(total_records / per_page) if total_records > 0 else 1

    offset = (page - 1) * per_page

    # Retrieve paginated devices
    cursor.execute(
        """
        SELECT
            id,
            hostname,
            ip_address,
            operating_system,
            status,
            registered_at
        FROM devices
        WHERE
            deleted = 0
            AND (
                hostname LIKE ?
                OR ip_address LIKE ?
                OR operating_system LIKE ?
                OR status LIKE ?
            )
        ORDER BY registered_at DESC
        LIMIT ?
        OFFSET ?
        """,
        (
            search_value,
            search_value,
            search_value,
            search_value,
            per_page,
            offset
        )
    )

    rows = cursor.fetchall()

    connection.close()

    devices = []

    for row in rows:

        devices.append({
            "id": row["id"],
            "hostname": row["hostname"],
            "ip_address": row["ip_address"],
            "operating_system": row["operating_system"],
            "status": row["status"],
            "registered_at": row["registered_at"]
        })

    return {
        "status": "success",
        "page": page,
        "per_page": per_page,
        "total_records": total_records,
        "total_pages": total_pages,
        "has_previous": page > 1,
        "has_next": page < total_pages,
        "devices": devices
    }, 200

    # Retrieve Single Device Service

def get_device_service(device_id):
    """
    Responsibility:
        Retrieve detailed information for a single registered device
        using its unique identifier.

    Business Rules:
        • Only authenticated users may retrieve device information.
        • The requested device must exist.
        • Disabled devices can still be retrieved.
        • Only the required device fields are returned.
        • No audit log is required.

    Returns:
        The requested device details.
    """

    connection = get_db_connection()

    cursor = connection.cursor()

    cursor.execute(
        """
        SELECT
            id,
            hostname,
            ip_address,
            operating_system,
            status,
            registered_at
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    device = cursor.fetchone()

    connection.close()

    if not device:

        return {
            "status": "error",
            "message": "Device not found"
        }, 404

    return {
        "status": "success",
        "message": "Device retrieved successfully",
        "device": {
            "id": device["id"],
            "hostname": device["hostname"],
            "ip_address": device["ip_address"],
            "operating_system": device["operating_system"],
            "status": device["status"],
            "registered_at": device["registered_at"]
        }
    }, 200


def update_device_service(
    device_id,
    current_user_id,
    current_username,
    data
):
    """
    Responsibility:
        Update an existing registered device.

    Business Rules:
        • Only authenticated users may update devices.
        • Device must exist.
        • Hostname is required.
        • IP address is required.
        • Operating system is required.
        • Status is required.
        • IP address must be valid.
        • IP address must remain unique.
        • Status must be one of the allowed device statuses.
        • Record the update in the audit log.

    Returns:
        Updated device information.
    """

    hostname = data.get("hostname")
    ip_address = data.get("ip_address")
    operating_system = data.get("operating_system")
    status = data.get("status")

    # Required fields
    if not hostname or not ip_address or not operating_system or not status:

        return {
            "status": "error",
            "message": "Hostname, IP address, operating system and status are required."
        }, 400

    # Validate IP Address
    try:

        ipaddress.ip_address(ip_address)

    except ValueError:

        return {
            "status": "error",
            "message": "Invalid IP address."
        }, 400

    # Validate status
    if status not in ALLOWED_DEVICE_STATUSES:

        return {
            "status": "error",
            "message": "Invalid device status."
        }, 400

    connection = get_db_connection()

    cursor = connection.cursor()

    # Check device exists
    cursor.execute(
        """
        SELECT *
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    existing_device = cursor.fetchone()

    if not existing_device:

        connection.close()

        return {
            "status": "error",
            "message": "Device not found."
        }, 404

    # Ensure IP address is unique (excluding this device)
    cursor.execute(
        """
        SELECT id
        FROM devices
        WHERE ip_address = ?
        AND id != ?
        """,
        (
            ip_address,
            device_id
        )
    )

    duplicate_ip = cursor.fetchone()

    if duplicate_ip:

        connection.close()

        return {
            "status": "error",
            "message": "IP address already exists."
        }, 409

    # Update the device
    cursor.execute(
        """
        UPDATE devices
        SET
            hostname = ?,
            ip_address = ?,
            operating_system = ?,
            status = ?
        WHERE id = ?
        """,
        (
            hostname,
            ip_address,
            operating_system,
            status,
            device_id
        )
    )

    connection.commit()

    # Retrieve updated device
    cursor.execute(
        """
        SELECT *
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    updated_device = cursor.fetchone()

    connection.close()

    # Audit Log
    log_activity(
        current_user_id,
        current_username,
        f"Updated device '{hostname}'"
    )

    return {
        "status": "success",
        "message": "Device updated successfully.",
        "device": {
            "id": updated_device["id"],
            "hostname": updated_device["hostname"],
            "ip_address": updated_device["ip_address"],
            "operating_system": updated_device["operating_system"],
            "status": updated_device["status"],
            "registered_at": updated_device["registered_at"]
        }
    }, 200


# Update Device Status Service

def update_device_status_service(
    current_user_id,
    current_username,
    device_id,
    data
):
    """
    Update the status of a device.
    """

    status = data.get("status")

    # Validate status
    if status not in ALLOWED_DEVICE_STATUSES:
        return {
            "status": "error",
            "message": "Invalid device status"
        }, 400

    # Connect to database
    connection = get_db_connection()

    cursor = connection.cursor()

    # Check if the device exists
    cursor.execute(
        """
        SELECT *
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    device = cursor.fetchone()

    if not device:

        connection.close()

        return {
            "status": "error",
            "message": "Device not found"
        }, 404

    # Update device status
    cursor.execute(
        """
        UPDATE devices
        SET status = ?
        WHERE id = ?
        """,
        (status, device_id)
    )

    connection.commit()

    # Retrieve the updated device
    cursor.execute(
        """
        SELECT *
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    updated_device = cursor.fetchone()

    action = (

        "Enabled"

        if status == "active"

        else "Disabled"

    )

    log_activity(

        current_user_id,

        current_username,

        f"{action} device '{updated_device['hostname']}'"

    )

    connection.close()

    return {
        "status": "success",
        "message": "Device status updated successfully",
        "device": {
            "id": updated_device["id"],
            "hostname": updated_device["hostname"],
            "status": updated_device["status"]
        }
    }, 200


  # Retrieve Device Logs Service

def get_device_logs_service(device_id):
    """
    Retrieve all logs for a specific device.
    """

    connection = get_db_connection()

    cursor = connection.cursor()

    # Verify device exists
    cursor.execute(
        """
        SELECT *
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    device = cursor.fetchone()

    if not device:

        connection.close()

        return {
            "status": "error",
            "message": "Device not found"
        }, 404
    
    cursor.execute(
        """
        SELECT *
        FROM logs
        WHERE device_id = ?
        """,
        (device_id,)
    )

    rows = cursor.fetchall()

    connection.close()

    logs = []

    for row in rows:

        logs.append({
            "id": row["id"],
            "timestamp": row["timestamp"],
            "event": row["event"],
            "severity": row["severity"],
            "status": row["status"],
            "archived": bool(row["archived"])
        })

    return {
            "status": "success",
            "device_id": device_id,
            "total_logs": len(logs),
            "logs": logs
    }, 200

def delete_device_service(
    current_user_id,
    current_username,
    device_id
):
    """
    Responsibility:
        Soft delete a registered device.

    Business Rules:
        • Only authenticated users may delete devices.
        • Device must exist.
        • Device must not already be deleted.
        • Soft delete by setting deleted = 1.
        • Record deletion timestamp.
        • Record the action in the audit log.

    Returns:
        Success or error response.
    """

    connection = get_db_connection()

    cursor = connection.cursor()

    # Check device exists
    cursor.execute(
        """
        SELECT *
        FROM devices
        WHERE id = ?
        """,
        (device_id,)
    )

    device = cursor.fetchone()

    if not device:

        connection.close()

        return {
            "status": "error",
            "message": "Device not found."
        }, 404

    # Already deleted?
    if device["deleted"] == 1:

        connection.close()

        return {
            "status": "error",
            "message": "Device has already been deleted."
        }, 400

    timestamp = (
        datetime.now(timezone.utc)
        .isoformat()
        .replace("+00:00", "Z")
    )

    # Soft delete
    cursor.execute(
        """
        UPDATE devices
        SET
            deleted = 1,
            deleted_at = ?
        WHERE id = ?
        """,
        (
            timestamp,
            device_id
        )
    )

    connection.commit()

    # Audit log
    log_activity(
        current_user_id,
        current_username,
        f"Deleted device '{device['hostname']}'"
    )

    connection.close()

    return {
        "status": "success",
        "message": "Device deleted successfully."
    }, 200