import { useEffect, useState } from "react";

import {
    getAlerts,
    updateAlertStatus
} from "../services/alertService";
import "../styles/alerts.css";


function Alerts() {

    const [alerts, setAlerts] = useState([]);

    const [loading, setLoading] = useState(true);


    // =====================================================
    // LOAD ALERTS
    // =====================================================

    async function loadAlerts() {

        try {

            setLoading(true);

            const data = await getAlerts();

            console.log("Alerts:", data);


            if (data.status === "success") {

                setAlerts(data.alerts || []);

            }

        } catch (error) {

            console.error(
                "Failed to load alerts:",
                error
            );

        } finally {

            setLoading(false);

        }

    }

    // =====================================================
    // CHANGE ALERT STATUS
    // =====================================================

    async function handleChangeAlertStatus(alert) {

        let newStatus;


        // Active → Acknowledged
        if (alert.status === "active") {

            newStatus = "acknowledged";

        }

        // Acknowledged → Resolved
        else if (alert.status === "acknowledged") {

            newStatus = "resolved";

        }

        // Resolved alerts cannot change
        else {

            return;

        }


        try {

            console.log(
                `Changing alert ${alert.id} status to ${newStatus}`
            );


            const data = await updateAlertStatus(
                alert.id,
                newStatus
            );


            console.log(
                "Alert status update:",
                data
            );


            if (data.status === "success") {

                // Reload alerts
                await loadAlerts();

            } else {

                console.error(
                    "Failed to change alert status:",
                    data.message
                );

            }

        } catch (error) {

            console.error(
                "Failed to change alert status:",
                error
            );

        }

    }


    // =====================================================
    // LOAD ALERTS WHEN PAGE OPENS
    // =====================================================

    useEffect(() => {

        loadAlerts();

    }, []);


    // =====================================================
    // PAGE
    // =====================================================

    return (

      <div className="alerts-page">


          {/* =====================================================
              PAGE HEADER
          ===================================================== */}

          <div className="alerts-page-header">

              <div>

                  <h1>
                      Security Alerts
                  </h1>

                  <p>
                      Monitor security alerts generated by CyberWatch.
                  </p>

              </div>

          </div>


          {/* =====================================================
              ALERT SUMMARY
          ===================================================== */}

          <div className="alert-summary">

              <div className="alert-summary-card">

                  <h3>
                      Total Alerts
                  </h3>

                  <span>
                      {alerts.length}
                  </span>

              </div>


              <div className="alert-summary-card">

                  <h3>
                      Active
                  </h3>

                  <span>
                      {
                          alerts.filter(
                              (alert) =>
                                  alert.status === "active"
                          ).length
                      }
                  </span>

              </div>


              <div className="alert-summary-card">

                  <h3>
                      High Severity
                  </h3>

                  <span>
                      {
                          alerts.filter(
                              (alert) =>
                                  alert.severity === "high"
                          ).length
                      }
                  </span>

              </div>

          </div>


          {/* =====================================================
              ALERT LIST
          ===================================================== */}

          <div className="alert-list-card">


              <div className="alert-list-header">

                  <h2>
                      Alert Center
                  </h2>

                  <p>
                      Security events requiring attention
                  </p>

              </div>


              {loading ? (

                  <div className="alert-empty">

                      <div className="alert-empty-icon">
                          ⏳
                      </div>

                      <h3>
                          Loading Alerts
                      </h3>

                      <p>
                          Please wait while CyberWatch retrieves alerts.
                      </p>

                  </div>

              ) : alerts.length === 0 ? (

                  <div className="alert-empty">

                      <div className="alert-empty-icon">
                          🛡️
                      </div>

                      <h3>
                          No Security Alerts
                      </h3>

                      <p>
                          CyberWatch has not detected any alerts requiring attention.
                      </p>

                  </div>

              ) : (

                  alerts.map((alert) => (

                      <div
                          className="alert-item"
                          key={alert.id}
                      >

                          <h3>
                              {alert.title}
                          </h3>

                          <p>
                              {alert.message}
                          </p>


                          <div className="alert-meta">

                            <span
                                className={`alert-severity ${alert.severity}`}
                            >
                                {alert.severity}
                            </span>


                            <span
                                className={`alert-status ${alert.status}`}
                            >
                                {alert.status}
                            </span>

                        </div>

                        <div className="alert-actions">

                            {alert.status === "active" && (

                                <button
                                    type="button"
                                    className="alert-action-btn acknowledge-btn"
                                    onClick={() =>
                                        handleChangeAlertStatus(alert)
                                    }
                                >
                                    🔍 Acknowledge
                                </button>

                            )}


                            {alert.status === "acknowledged" && (

                                <button
                                    type="button"
                                    className="alert-action-btn resolve-btn"
                                    onClick={() =>
                                        handleChangeAlertStatus(alert)
                                    }
                                >
                                    ✅ Resolve
                                </button>

                            )}


                            {alert.status === "resolved" && (

                                <span className="alert-resolved-label">
                                    ✓ Resolved
                                </span>

                            )}

                        </div>

                      </div>

                  ))

              )}

          </div>


      </div>

  );

}


export default Alerts;