import { useEffect, useState } from "react";

import {
    getAlerts,
    updateAlertStatus
} from "../services/alertService";

import ViewAlertModal from "../components/ViewAlertModal";

import "../styles/alerts.css";


function Alerts() {

    const [alerts, setAlerts] = useState([]);

    const [loading, setLoading] = useState(true);


    // =====================================================
    // VIEW ALERT STATE
    // =====================================================

    const [showViewModal, setShowViewModal] = useState(false);

    const [selectedAlert, setSelectedAlert] = useState(null);


    // =====================================================
    // LOAD ALERTS
    // =====================================================

    async function loadAlerts() {

        try {

            setLoading(true);

            const data = await getAlerts();

            console.log(
                "Alerts:",
                data
            );


            if (data.status === "success") {

                setAlerts(
                    data.alerts || []
                );

            }

        } catch (error) {

            console.error(
                "Failed to load alerts:",
                error
            );

        } finally {

            setLoading(false);

        }

    }


    // =====================================================
    // VIEW ALERT
    // =====================================================

    function handleViewAlert(alert) {

        setSelectedAlert(alert);

        setShowViewModal(true);

    }


    // =====================================================
    // CLOSE VIEW ALERT MODAL
    // =====================================================

    function handleCloseViewAlert() {

        setShowViewModal(false);

        setSelectedAlert(null);

    }


    // =====================================================
    // CHANGE ALERT STATUS
    // =====================================================

    async function handleChangeAlertStatus(alert) {

        let newStatus;


        // -------------------------------------------------
        // ACTIVE → ACKNOWLEDGED
        // -------------------------------------------------

        if (alert.status === "active") {

            newStatus = "acknowledged";

        }


        // -------------------------------------------------
        // ACKNOWLEDGED → RESOLVED
        // -------------------------------------------------

        else if (alert.status === "acknowledged") {

            newStatus = "resolved";

        }


        // -------------------------------------------------
        // RESOLVED → NO CHANGE
        // -------------------------------------------------

        else {

            return;

        }


        try {

            console.log(
                `Changing alert ${alert.id} status to ${newStatus}`
            );


            const data = await updateAlertStatus(
                alert.id,
                newStatus
            );


            console.log(
                "Alert status update:",
                data
            );


            if (data.status === "success") {

                // Reload alerts after status change
                await loadAlerts();

            } else {

                console.error(
                    "Failed to change alert status:",
                    data.message
                );

            }

        } catch (error) {

            console.error(
                "Failed to change alert status:",
                error
            );

        }

    }


    // =====================================================
    // LOAD ALERTS WHEN PAGE OPENS
    // =====================================================

    useEffect(() => {

        loadAlerts();

    }, []);


    // =====================================================
    // PAGE
    // =====================================================

    return (

        <div className="alerts-page">


            {/* =====================================================
                PAGE HEADER
            ===================================================== */}

            <div className="alerts-page-header">

                <div>

                    <h1>
                        Security Alerts
                    </h1>

                    <p>
                        Monitor security alerts generated by CyberWatch.
                    </p>

                </div>

            </div>


            {/* =====================================================
                ALERT SUMMARY
            ===================================================== */}

            <div className="alert-summary">


                {/* TOTAL ALERTS */}

                <div className="alert-summary-card">

                    <h3>
                        Total Alerts
                    </h3>

                    <span>
                        {alerts.length}
                    </span>

                </div>


                {/* ACTIVE ALERTS */}

                <div className="alert-summary-card">

                    <h3>
                        Active
                    </h3>

                    <span>

                        {
                            alerts.filter(
                                (alert) =>
                                    alert.status === "active"
                            ).length
                        }

                    </span>

                </div>


                {/* HIGH SEVERITY */}

                <div className="alert-summary-card">

                    <h3>
                        High Severity
                    </h3>

                    <span>

                        {
                            alerts.filter(
                                (alert) =>
                                    alert.severity === "high"
                            ).length
                        }

                    </span>

                </div>


            </div>


                    {/* =====================================================
            ALERT LIST
        ===================================================== */}

        <div className="alert-list-card">


            {/* =================================================
                ALERT LIST HEADER
            ================================================= */}

            <div className="alert-list-header">

                <h2>
                    Alert Center
                </h2>

                <p>
                    Security events requiring attention
                </p>

            </div>


            {/* =================================================
                SCROLLABLE ALERT AREA
            ================================================= */}

            <div className="alert-list-scroll">


                {/* =================================================
                    LOADING
                ================================================= */}

                {loading ? (

                    <div className="alert-empty">

                        <div className="alert-empty-icon">
                            ⏳
                        </div>

                        <h3>
                            Loading Alerts
                        </h3>

                        <p>
                            Please wait while CyberWatch retrieves alerts.
                        </p>

                    </div>

                )


                /* =================================================
                  NO ALERTS
                ================================================= */

                : alerts.length === 0 ? (

                    <div className="alert-empty">

                        <div className="alert-empty-icon">
                            🛡️
                        </div>

                        <h3>
                            No Security Alerts
                        </h3>

                        <p>
                            CyberWatch has not detected any alerts requiring attention.
                        </p>

                    </div>

                )


                /* =================================================
                  ALERTS
                ================================================= */

                : (

                    alerts.map((alert) => (

                        <div
                            className="alert-item"
                            key={alert.id}
                        >


                            {/* =================================================
                                ALERT INFORMATION
                            ================================================= */}

                            <h3>
                                {alert.title}
                            </h3>


                            <p>
                                {alert.message}
                            </p>


                            {/* =================================================
                                SEVERITY
                            ================================================= */}

                            <span
                                className={`alert-severity ${alert.severity}`}
                            >
                                {alert.severity}
                            </span>


                            {/* =================================================
                                STATUS
                            ================================================= */}

                            <span
                                className={`alert-status ${alert.status}`}
                            >
                                {alert.status}
                            </span>


                            {/* =================================================
                                ALERT ACTIONS
                            ================================================= */}

                            <div className="alert-actions">


                                {/* -----------------------------------------
                                    VIEW
                                ----------------------------------------- */}

                                <button
                                    type="button"
                                    className="alert-action-btn view-alert-btn"
                                    title="View Alert"
                                    onClick={() =>
                                        handleViewAlert(alert)
                                    }
                                >
                                    👁 View
                                </button>


                                {/* -----------------------------------------
                                    ACKNOWLEDGE
                                ----------------------------------------- */}

                                {alert.status === "active" && (

                                    <button
                                        type="button"
                                        className="alert-action-btn acknowledge-btn"
                                        title="Acknowledge Alert"
                                        onClick={() =>
                                            handleChangeAlertStatus(alert)
                                        }
                                    >
                                        🔍 Acknowledge
                                    </button>

                                )}


                                {/* -----------------------------------------
                                    RESOLVE
                                ----------------------------------------- */}

                                {alert.status === "acknowledged" && (

                                    <button
                                        type="button"
                                        className="alert-action-btn resolve-btn"
                                        title="Resolve Alert"
                                        onClick={() =>
                                            handleChangeAlertStatus(alert)
                                        }
                                    >
                                        ✅ Resolve
                                    </button>

                                )}


                                {/* -----------------------------------------
                                    RESOLVED
                                ----------------------------------------- */}

                                {alert.status === "resolved" && (

                                    <span className="alert-resolved-label">
                                        ✓ Resolved
                                    </span>

                                )}


                            </div>


                        </div>

                    ))

                )}


            </div>

            </div>

{/* =====================================================
                VIEW ALERT MODAL
            ===================================================== */}

            <ViewAlertModal

                isOpen={showViewModal}

                alert={selectedAlert}

                onClose={handleCloseViewAlert}

            />


        </div>

    );

}


export default Alerts;